## Multiclass Case

In [1]:
# libraries
import numpy as np

In [93]:
# other test variables, which are self parameters
# classes schould be given as int from 0 to k
n_total_ftr = 0
target_values = [1,2,3,4,5,6,7,8,9,0]
mu = np.ones((n_total_ftr, len(target_values))) * 0
sigma = np.ones((n_total_ftr, len(target_values))) * 1
penalty_s = 0.01
penalty_r = 0.01
epochs = 1
lr_mu = 0.01
lr_sigma = 0.01
monte_carlo = 5 #10000

# create 3d array with all r for current observation 
# r^cl_j = r[l, j, c]
#needs to be specified only if we got right model
#r = np.random.randn(monte_carlo, n_total_ftr, len(target_values))

# maybe set param amount_classes from target_values

In [132]:
def __help_softmax(array_eta, class_eta):
    """
        Calculates the softmax equation for given class etas and searched etas
        :param array_eta: (np.ndarray) Array with etas of all classes
    """
    

In [ ]:
def __softmax(x,y): # needs self in model
    """
        Update the distribution parameters mu and sigma by optimizing them in terms of the (log) likelihood.
        Here we assume a Bernoulli distributed target variable. We use a Probit model as our base model.
        This corresponds to the FIRES-GLM model in the paper.

        :param x: (np.ndarray) Batch of observations (numeric values only, consider normalizing data for better results)
        :param y: (np.ndarray) Batch of labels: type integer e.g. 1,2,3,4 usw
     """

     for epoch in range(epochs): #changed to self.epoch in model
         # Shuffle the observations
         random_idx = np.random.permutation(len(y))
         x = x[random_idx]
         y = y[random_idx]

         #maybe loop over all given observations
         x = x[0]
         y = y[0]
         # Iterative update of mu and sigma
         try:
             # l number of samples, j features, c classes
             # create 3d array with all r for current observation 
             # r^cl_j = r[l, j, c] lxjxc
             r = np.random.randn(monte_carlo, n_total_ftr, len(target_values))
             # we only change the psi for the actuall given class still need all classes of course
             # r = np.random.randn(monte_carlo, n_total_ftr)

             print(r.shape)
             # calculate thetas for all samples and classes theta^cl_jt = theta[l,j,c]
             # lxjxc
             theta = r * sigma + mu

             #calculate all the etas
             eta = np.einsum("ljc,j->ljc", theta, x) # multiply all ftr_cols with given ftr_vector x
             eta = np.einsum("ljc->lc", eta) #sum up all theta^cl_j * x_tj so we got l samples for all c classes
             eta = np.exp(eta) # we only need them exp
             eta_sum = np.einsum("lc->l", eta) #sum up etas for the l samples
             
             #calculate softmax only for observed class
             softmax_lh = (eta[:,y].T / eta_sum).T  #lxo o is amount of given observations
             
             marginal = np.einsum("lo->o", softmax_lh) / monte_carlo # 1xy


             # calculate derivatives nabla_mu, nabla_sigma must be handled better

             #first calculate softmax dtheta

             softmax_derivative = 
             


In [ ]:
#for getting gaussnorm r ~ N(0,1) size samples x features
test = np.random.randn(10000,100)
print(test)
print(test[1])
print(test[9, 9])

In [ ]:
#how to calculate theta^cl_t
print(np.array([1,2,3,4,5]) * np.array([2,3,4,5,6]) + np.ones(5))

#for sampling create Matrix with all r monte_carlo X 


In [ ]:
# get theta at time t and for all featurs for class c is number of feature
theta_c = sigma[:,c] * np.random.randn(total_features) + mu[:,c]

In [38]:
bla = np.array([1,2,3,4])
np.sum(np.exp(bla))
bla2 = np.array((2,4,6))
np.einsum("i,j->ij", bla, bla2) * bla2

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 6, 12, 18],
       [ 8, 16, 24]])

In [43]:
(np.einsum("j,l->jl", bla, bla2) * bla2) / bla2

array([[ 2.,  4.,  6.],
       [ 4.,  8., 12.],
       [ 6., 12., 18.],
       [ 8., 16., 24.]])

In [61]:
# tests for derivative o = 3, j = 4, l = 5 entries
X = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
print(X)
eta = np.array([[1,2,3,4,5], [2,2,2,2,2], [3,3,3,3,3]])
sums_eta = np.array((5,5,5,5,5))
x_eta = np.einsum("oj,ol->ojl", X, eta)
print(x_eta)
np.einsum("ojl,ol->ojl", x_eta, (sums_eta-eta)) / sums_eta

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]
  [9 9 9 9 9]]]


array([[[0.8, 1.2, 1.2, 0.8, 0. ],
        [0.8, 1.2, 1.2, 0.8, 0. ],
        [0.8, 1.2, 1.2, 0.8, 0. ],
        [0.8, 1.2, 1.2, 0.8, 0. ]],

       [[2.4, 2.4, 2.4, 2.4, 2.4],
        [2.4, 2.4, 2.4, 2.4, 2.4],
        [2.4, 2.4, 2.4, 2.4, 2.4],
        [2.4, 2.4, 2.4, 2.4, 2.4]],

       [[3.6, 3.6, 3.6, 3.6, 3.6],
        [3.6, 3.6, 3.6, 3.6, 3.6],
        [3.6, 3.6, 3.6, 3.6, 3.6],
        [3.6, 3.6, 3.6, 3.6, 3.6]]])

In [54]:
sums_eta - eta

array([[4, 3, 2, 1, 0],
       [3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2]])

In [ ]:
test = np.random.randn(2,3,4) #monte, features, classes
print(test.shape)
print("----------")
print(test[1])
print("-------")
print(test[1,1])
print("--------")
print(test[1,:,1])

In [3]:
test = np.array([[(1,2),(3,4)], [(5,6),(7,8)]])
ones = np.ones((2,2))
twos = np.ones((2,2)) * 2

In [4]:
test * twos + ones

array([[[ 3.,  5.],
        [ 7.,  9.]],

       [[11., 13.],
        [15., 17.]]])

In [4]:
test1 = test[0]
#print(test1)
#(test1.T * np.array([1,2])).T


In [9]:
c = np.einsum("ij,i->ij", test1, np.array((1,2)))
print(c)
c[0,1] #feature class

[[1 2]
 [6 8]]


2

In [5]:
test1

array([[1, 2],
       [3, 4]])

In [6]:
np.einsum("ij->j", test1) # for nabla

array([4, 6])

In [7]:
np.einsum("ij->i", test1)

array([3, 7])

In [101]:
test

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [102]:
blub = np.einsum("ijk->ik", test)
print(blub) # -> blub[sample, class]
blub[0, 1]

[[ 4  6]
 [12 14]]


6

In [ ]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
a
print(test)
test2 = np.einsum("ijk,j->ijk", test, np.array((1,2)))


In [127]:
#test for softmax

def fun_test(x):
    print(x)
    result = np.empty(len(x))
    sum_all = np.sum(x)
    print(sum_all)
    for idx, entry in enumerate(x):
        result[idx] = entry/sum_all
    print("result: ", result)
    return result


fun_test_v = np.vectorize(fun_test)

test_array = np.array([[1,2],[3,4],[5,6]], dtype=np.float)

for idx, x in enumerate(test_array):
    test_array[idx] = fun_test(x)

test_array

[1. 2.]
3.0
result:  [0.33333333 0.66666667]
[3. 4.]
7.0
result:  [0.42857143 0.57142857]
[5. 6.]
11.0
result:  [0.45454545 0.54545455]


array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857],
       [0.45454545, 0.54545455]])

In [2]:
a = np.array((1,2,3,4,5,6))
a / a

array([1., 1., 1., 1., 1., 1.])

In [25]:
# test for simultaneous caclculations
test_matrix = np.array([[1,2,3,4,5],
                        [1,2,3,4,5],
                        [1,2,3,4,5],
                        [1,2,3,4,5]])
test_matrix[:,[0,1,0,2,3]]
test_matrix.T / np.array((1,2,3,4))
np.exp(test_matrix)

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ],
       [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])


### Further Questions/ Tasks
- [x] softmax derivative
- [x] read softmax glm implementation again
- [x] check where class check happens
- [] is simultaneous calculation for all given observetions possible
- [] rewrite np.einsum indexes so they match l, j and c