In [91]:
# libraries
import numpy as np

In [93]:
# other test variables, which are self parameters
n_total_ftr = 0
target_values = [1,2,3,4,5,6,7,8,9,0]
mu = np.ones((n_total_ftr, len(target_values))) * 0
sigma = np.ones((n_total_ftr, len(target_values))) * 1
penalty_s = 0.01
penalty_r = 0.01
epochs = 1
lr_mu = 0.01
lr_sigma = 0.01
monte_carlo = 5 #10000

# create 3d array with all r for current observation 
# r^cl_j = r[l, j, c]
#needs to be specified only if we got right model
r = np.random.randn(monte_carlo, n_total_ftr, len(target_values))

# maybe set param amount_classes from target_values

In [132]:
def __help_softmax(array_eta):
    """
        Calculates the softmax equation for given class etas and searched etas
        :param array_eta: (np.ndarray) Array with etas of all classes
    """
    result = np.empty(len(x))
    sum_all = np.sum(x)
    print(sum_all)
    for idx, entry in enumerate(x):
        result[idx] = entry/sum_all
    print("result: ", result)
    return result

In [ ]:
def __softmax(x,y): # needs self in model
    """
        Update the distribution parameters mu and sigma by optimizing them in terms of the (log) likelihood.
        Here we assume a Bernoulli distributed target variable. We use a Probit model as our base model.
        This corresponds to the FIRES-GLM model in the paper.

        :param x: (np.ndarray) Batch of observations (numeric values only, consider normalizing data for better results)
        :param y: (np.ndarray) Batch of labels: type integer e.g. 1,2,3,4 usw
     """

     for epoch in range(epochs): #changed to self.epoch in model
         # Shuffle the observations
         random_idx = np.random.permutation(len(y))
         x = x[random_idx]
         y = y[random_idx]

         #maybe loop over all given observations
         x = x[0]
         y = y[0]
         # Iterative update of mu and sigma
         try:
             # create 3d array with all r for current observation 
             # r^cl_j = r[l, j, c]
             # r_t = np.random.randn(monte_carlo, n_total_ftr, len(target_values))
             print(r.shape)
             # calculate thetas for all samples and classes theta^cl_jt = theta[l,j,c]
             theta = r * sigma + mu 

             #calculate all the etas
             eta = np.einsum("ijk,j->ijk", theta, x) # multiply all ftr_cols with given ftr_vector x
             eta = np.einsum("ijk->ik", eta) #sum up all theta^cl_j * x_tj
             
             #calculate softmax 
             marginal_lh = np.empty(monte_carlo, len(target_values))
             for idx, sample in enumerate(eta):
                 marginal_lh[idx] = __help_softmax(sample)

             # calculate derivatives nabla_mu, nabla_sigma must be handled better
             nabla_mu = np.einsum("ij->j", marginal_lh)/monte_carlo # add all sample marginal likelihoods devide by monte carlo

             nabla_sigma = 


In [ ]:
#for getting gaussnorm r ~ N(0,1) size samples x features
test = np.random.randn(10000,100)
print(test)
print(test[1])
print(test[9, 9])

In [ ]:
#how to calculate theta^cl_t
print(np.array([1,2,3,4,5]) * np.array([2,3,4,5,6]) + np.ones(5))

#for sampling create Matrix with all r monte_carlo X 


In [ ]:
# get theta at time t and for all featurs for class c is number of feature
theta_c = sigma[:,c] * np.random.randn(total_features) + mu[:,c]

In [ ]:
bla = [1,2,3,4]
np.sum(np.exp(bla))

In [ ]:
test = np.random.randn(2,3,4) #monte, features, classes
print(test.shape)
print("----------")
print(test[1])
print("-------")
print(test[1,1])
print("--------")
print(test[1,:,1])

In [95]:
test = np.array([[(1,2),(3,4)], [(5,6),(7,8)]])
ones = np.ones((2,2))
twos = np.ones((2,2)) * 2

In [ ]:
test * twos + ones

In [96]:
test1 = test[0]
#print(test1)
#(test1.T * np.array([1,2])).T


In [ ]:
c = np.einsum("ij,i->ij", test1, np.array((1,2)))
print(c)
c[0,1] #feature class

In [98]:
test1

array([[1, 2],
       [3, 4]])

In [135]:
np.einsum("ij->j", test1) /2 # for nabla

array([2., 3.])

In [101]:
test

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [102]:
blub = np.einsum("ijk->ik", test)
print(blub) # -> blub[sample, class]
blub[0, 1]

[[ 4  6]
 [12 14]]


6

In [ ]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
a
print(test)
test2 = np.einsum("ijk,j->ijk", test, np.array((1,2)))


In [127]:
#test for softmax

def fun_test(x):
    print(x)
    result = np.empty(len(x))
    sum_all = np.sum(x)
    print(sum_all)
    for idx, entry in enumerate(x):
        result[idx] = entry/sum_all
    print("result: ", result)
    return result


fun_test_v = np.vectorize(fun_test)

test_array = np.array([[1,2],[3,4],[5,6]], dtype=np.float)

for idx, x in enumerate(test_array):
    test_array[idx] = fun_test(x)

test_array

[1. 2.]
3.0
result:  [0.33333333 0.66666667]
[3. 4.]
7.0
result:  [0.42857143 0.57142857]
[5. 6.]
11.0
result:  [0.45454545 0.54545455]


array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857],
       [0.45454545, 0.54545455]])

### Further Questions/ Tasks
- [] softmax derivative
- [] read softmax glm implementation again
- [] check where class check happens