## Test Multiclass perceptron

In [70]:
import numpy as np
class MCP():

    def __init__(self, n_features, n_classes, epochs=1, learning_rate=1):
        self.f = n_features
        self.l = n_classes
        self.N = epochs
        self.lr = learning_rate
        self.weights = self.__initialize_weights() 
        print(self.N)

    def __initialize_weights(self):
        weights = np.zeros((self.l, self.f))
        return weights

    def prediction(self, data_vector):
        print(data_vector)
        predictions = np.dot(self.weights, data_vector)
        return np.where(predictions == np.amax(predictions))[0][0]

    def train(self, train):
        for i in range(self.N):
            print(i)
            print(train)
            for example in train:
                label= example[1]
                doc  = example[0]
                comp_label = self.prediction(doc)
                print(f"comp_label: {comp_label}")
                if comp_label != label:
                    self.weights[comp_label] -= self.lr * doc
                    self.weights[label] += self.lr * doc 


In [50]:
import numpy as np
test = np.array([[1,1,1], [2,2,2], [3,3,3]])
test
x = np.array([1,2,3])
test[0] += x
test

array([[2, 3, 4],
       [2, 2, 2],
       [3, 3, 3]])

In [11]:
test

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
perc = MCP(2,3, epochs=50)

50


In [72]:
perc.weights

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [78]:
training_data = np.array([[1,1], [-1,2], [3,3], [-2,1], [-4,2], [-3, -2], [-1, -3]])
label_data = np.array((0,1,0,1,1,2,2))

In [79]:
test = tuple(zip(training_data, label_data))

In [81]:
for i in test:
    print(i)

(array([1, 1]), 0)
(array([-1,  2]), 1)
(array([3, 3]), 0)
(array([-2,  1]), 1)
(array([-4,  2]), 1)
(array([-3, -2]), 2)
(array([-1, -3]), 2)


In [82]:
test

((array([1, 1]), 0),
 (array([-1,  2]), 1),
 (array([3, 3]), 0),
 (array([-2,  1]), 1),
 (array([-4,  2]), 1),
 (array([-3, -2]), 2),
 (array([-1, -3]), 2))

In [83]:
perc.train(test)

0
((array([1, 1]), 0), (array([-1,  2]), 1), (array([3, 3]), 0), (array([-2,  1]), 1), (array([-4,  2]), 1), (array([-3, -2]), 2), (array([-1, -3]), 2))
[1 1]
comp_label: 0
[-1  2]
comp_label: 1
[3 3]
comp_label: 0
[-2  1]
comp_label: 2
[-4  2]
comp_label: 1
[-3 -2]
comp_label: 2
[-1 -3]
comp_label: 2
1
((array([1, 1]), 0), (array([-1,  2]), 1), (array([3, 3]), 0), (array([-2,  1]), 1), (array([-4,  2]), 1), (array([-3, -2]), 2), (array([-1, -3]), 2))
[1 1]
comp_label: 0
[-1  2]
comp_label: 1
[3 3]
comp_label: 0
[-2  1]
comp_label: 1
[-4  2]
comp_label: 1
[-3 -2]
comp_label: 2
[-1 -3]
comp_label: 2
2
((array([1, 1]), 0), (array([-1,  2]), 1), (array([3, 3]), 0), (array([-2,  1]), 1), (array([-4,  2]), 1), (array([-3, -2]), 2), (array([-1, -3]), 2))
[1 1]
comp_label: 0
[-1  2]
comp_label: 1
[3 3]
comp_label: 0
[-2  1]
comp_label: 1
[-4  2]
comp_label: 1
[-3 -2]
comp_label: 2
[-1 -3]
comp_label: 2
3
((array([1, 1]), 0), (array([-1,  2]), 1), (array([3, 3]), 0), (array([-2,  1]), 1), (arr

In [40]:
test

In [48]:
bla = np.array([[1,1,1], [2,2,2]])
x = np.array((1,2))
np.dot(bla.T,x)

array([5, 5, 5])

In [76]:
perc.weights


array([[ 4.,  1.],
       [-1.,  1.],
       [-3., -2.]])

In [88]:
perc.prediction(np.array((-1,0)))

[-1  0]


1